### ISSUE TITLE
Fehler: Artikel > "Mehrere bearbeiten" > Seitenbäume

### ISSUE THREAD

**Issue by johannes-bittner** [psi-4ward/boxes4ward#10]
Ich habe eine Contao-Installation (2.11.2), in der drei Domains mit mehreren Sprachbäumen (1x DE/FR, 1xDE/FR/EN, 1xDE) verwaltet werden. Wenn ich dort die Artikel einer Kategorie über "Mehrere bearbeiten" bearbeiten möchte, tritt das folgende Phänomen auf: Beim Klicken auf Seitenbäume bzw. einen Seitenknoten (d.h. eine Seite, die weitere Unterseiten hat), wird der Baum bzw. Baumteil nicht geschlossen, sondern die Seiten erscheinen doppelt, d.h. der Baum bzw. Baumteil wird darunter wiederholt. (Die Artikel, um die es geht, werden dabei zwar in verschiedenen Sprachbäumen, aber jeweils nur innerhalb einer Domain verwendet.)

**Comment by psi-4ward** [comment]
tritt der Fehler in Contao3 auch auf?
Bei 2.11 fixe ich nur noch kritische Sachen

**Comment by johannes-bittner** [comment]
Hallo Christoph, 

habe ich bislang nicht testen können, weil die betreffende Seite noch unter Contao 2.11 läuft.

Gruß

Johannes
