### ISSUE TITLE
Fehler bei der Einbindung eines BoxModules als Inhaltselement

### ISSUE THREAD

**Issue by bauer00** [psi-4ward/boxes4ward#11]
Wenn man ein BoxModul als Inhaltselement in einen Artikel einfügt erscheint eine weisse Seite und im error.log findet man folgende Zeile:
PHP Fatal error:  Class 'Psi\Boxes4ward\Module\BackendTemplate' not found in /data/www/dachser/website/system/modules/boxes4ward/Module/Boxes4ward.php on line 32

Hier wurde einfach in der Klasse Boxes4ward vergessen bei der instanzierung von BackendTemplate der Namespace, in dem Fall einfach \BackendTemplate anzugeben.

**Comment by psi-4ward** [comment]
fixed in 2358aa603864e5d2b9970cb4f368799cada9f122
