### ISSUE TITLE
Content not displayed because tl_content contains "do"="article" instead of "do"="boxes4ward"

### ISSUE THREAD

**Issue by ghost** [psi-4ward/boxes4ward#12]
- Contao 3.1.1
- create new article in addition to existing articles in an existing category
- add content elements
- content not visible
- checking tl_content for these content elements:
  - "ptable" is set to "tl_boxes4ward_article"
  - "do" is net to "article"
  - changing "do" to "boxes4ward" 
- content is now displayed

I have not examined the cause, yet.

**Comment by psi-4ward** [comment]
You need NO GlobalContentelements for Contao 3.x so theres no `do` row anymore.
This is a core feature and boxes4ward set the right `ptable` column.

**Comment by ghost** [comment]
Thx, updated the database and boxes4ward code. I installed boxes4ward in a version from mid july. Now working.

**Comment by ghost** [comment]
I did not use GlobalContentelements since it's not possible.
