### ISSUE TITLE
Bilder werden nicht angezeigt

### ISSUE THREAD

**Issue by kreativsoehne** [psi-4ward/boxes4ward#15]
Hallo,

nach einem Contao-Update auf 3.2.9 funktionieren in den Boxen keine Bilder mehr.
Die Auswahl einer Bild-Quelldatei bleibt auch nach Auswahl leer.
Ich vermute das dies an der geänderten Dateibehandlung in Contao liegt.

Viele Grüße

**Comment by psi-4ward** [comment]
Die Github Version genommen oder ER?

**Comment by kreativsoehne** [comment]
Github :)

**Comment by kreativsoehne** [comment]
Hallo, ich habe den Fehler gefunden... Entwarnung es liegt nicht an eurem Modul, auch wenn die Vermutung sehr nahe lag, war es ein Fehler in der DB.
https://community.contao.org/de/showthread.php?46555-Gel%F6st-Es-wird-kein-Bild-zum-Artikel-Newsletter-etc-%FCbernommen

Sorry für den Fehlalarm.
