### ISSUE TITLE
CSS ID/Klasse bei Boxen/Artikeln/Elementen hinzufügen?

### ISSUE THREAD

**Issue by Christoph1987** [psi-4ward/boxes4ward#3]
- Wäre es möglich bei Artikeln & Elementen zusätzlich "CSS-ID/Klasse" eingebbar zu machen.
- Und könnte man das auch bei den "Boxen Kategorien" generell auch eine CSS-ID/Klasse eingebbar machen?
- Dann fände ich es gut, wenn jedes Element automatisch eine Standardklasse hätte wie z.B. ".mod_boxes4ward_element". Ähnlich wie bei der boxes Erweiterung "mod_box_items". So kann man die alle auf einmal stylen.

**Comment by psi-4ward** [comment]
> Und könnte man das auch bei den "Boxen Kategorien" generell auch eine CSS-ID/Klasse eingebbar machen?

Du kannst im Modul eine Klasse/ID mitgeben. Die anderen zwei Punkte sind implementiert.
