### ISSUE TITLE
Boxen anzeigen nach Wochentag(en)

### ISSUE THREAD

**Issue by saress** [psi-4ward/boxes4ward#7]
Praktisch ist das vor allem für Seiten, die beispielsweise täglich wechselnde Angebote haben und wäre daher sicher auch eine gute Ergänzung für das boxes4ward Modul.

**Comment by psi-4ward** [comment]
Soetwas hatte ich auch schon im Kopf aber um diese Anforderung umgreifend umzusetzen müsste man dann auch Uhrzeiten beachten oder? Wie sieht es mit Jahreszeiten, Monaten etc aus?

**Comment by saress** [comment]
Wir haben das damals sehr einfach gehalten und auf Basis der aktuellen Systemzeit einfach den Tag extrahiert und diesen mit den im Modul ausgewählten Tagen verglichen und die Ansichten dann entsprechend angepasst. Natürlich sollte der Server entsprechend das richtige Datum zurückliefern ;-) 

Damit war es dann einfach möglich zu sagen, dass eine Box am Montag, Dienstag und Freitag etc. angezeigt werden soll. Ein weitergehender Check nach Uhrzeit wäre dann natürlich noch etwas feiner abgestimmt, sollte aber vom Prinzip her gleich einfach funktionieren und würde noch zusätzliche Möglichkeiten eröffnen.

**Comment by psi-4ward** [comment]
implmentend weekday and month filter in 9623e91840a968d9b6086205f47be7e1b77d3fad
