### ISSUE TITLE
Wrapper Div nur wenn Contentelemente>0

### ISSUE THREAD

**Issue by thescrat** [psi-4ward/boxes4ward#8]
Hi Christoph,

wäre es nicht sinnvoll den Div-Wrapper einer jeden Inhaltsbox nur zu zeigen, wenn es auch Contentelemente darin gibt?

Da allerdings erfährt man das ja - leider - erst zu einem Zeitpunkt wenn der Wrapper bereits gebaut ist - Zeile 139.

**Comment by kikmedia** [comment]
Should have been implemented in 771bdc11a82e121842d1b399c07b9d099dde1ea7 - is there a malfunction?

**Comment by thescrat** [comment]
Es gibt 2 Wrapper. Einmal den äußersten (mod_boxes4ward), welcher nicht angezeigt wird, wenn $this->content leer ist. Aber innerhalb dieses Wrappers gibt es ja die einzelnen Divs (boxes4ward_article) die auch ohne Contentelemente leer dargestellt werden. Und um diese Wrapper geht es.
